# Basic profile service requests

### Get All profiles
GET http://localhost:8000/api/profiles
### Get Specific profile
GET http://localhost:8000/api/profiles/01

### Add a profile
POST http://localhost:8000/api/profiles HTTP/1.1
Content-Type: application/json

{
    "id": "03",
    "username": "henri",
    "password": "parool",
    "bio": "Bio for Henri",
    "cuisines": ["Italian", "Mexican"],
    "likedIngredients": ["Cheese", "Tomato"],
    "dislikedIngredients": ["Onion", "Garlic"]
}

### Update a profile
PUT http://localhost:8000/api/profiles/03 HTTP/1.1
Content-Type: application/json

{
    "id": "03",
    "username": "fidan",
    "password": "parool",
    "bio": "Bio for Fidan",
    "cuisines": ["Chinese", "Indian"],
    "likedIngredients": ["Chicken", "Rice"],
    "dislikedIngredients": ["Fish", "Egg"]
}

### Delete a profile
DELETE http://localhost:8000/api/profiles/03


# Basic post service requests

### Get All Posts
GET http://localhost:8001/api/posts

### Get specific post
GET http://localhost:8001/api/posts/01

### Add a post
POST http://localhost:8001/api/posts HTTP/1.1
Content-Type: application/json

{
    "id": "05",
    "description": "Example Description",
    "imgUrl": "image2.jpg",
    "likes": 3,
    "createdAt": "2024-03-17",
    "postedById": "02",
    "tags": ["Vegan", "Gluten-free"]
}

### Update a post
PUT http://localhost:8001/api/posts/02 HTTP/1.1
Content-Type: application/json

{
    "id": "01",
    "description": "Updated Description",
    "imgUrl": "updated_image.jpg",
    "likes": 10,
    "createdAt": "2024-03-17",
    "postedById": "01",
    "tags": ["Vegetarian", "Gluten-free"]
}

### Delete a post
DELETE http://localhost:8001/api/posts/02

### Get all posts that an user has made
GET http://localhost:8001/api/profiles/01/posts

### Get a specific post made by a specific user
GET http://localhost:8001/api/profiles/01/posts/01


### Get all comments for a specific post
GET http://localhost:8001/api/posts/01/comments

### Add a comment to a specific post
POST http://localhost:8001/api/posts/01/comments HTTP/1.1
Content-Type: application/json

{   
    "id": "03",
    "text": "This is a comment",
    "createdAt": "2024-03-17T16:34:50.68211",
    "postedById": "01"
}

### Get a specific comment on a specific post
GET http://localhost:8001/api/posts/01/comments/03 HTTP/1.1
### api gateway
GET http://localhost:8080/api/posts/01/comments/03 HTTP/1.1

### Update a specific comment on a specific post
PUT http://localhost:8001/api/posts/01/comments/03 HTTP/1.1
Content-Type: application/json

{
    "id": "03",
    "text": "This is an updated comment",
    "createdAt": "2024-03-18T16:34:50.68211",
    "postedById": "01"
}

### Delete a comment
DELETE http://localhost:8001/api/posts/01/comments/03 HTTP/1.1


# Basic review service requests

### Get All reviews
GET http://localhost:8002/api/reviews

### Get Specific review
GET http://localhost:8002/api/reviews/01

### Add a review
POST http://localhost:8002/api/reviews HTTP/1.1
Content-Type: application/json

{
    "id": "07",
    "recipeId": "01",
    "createdAt": "2024-03-17",
    "postedBy": "20",
    "score": 5.7
}

### Update a review
PUT http://localhost:8002/api/reviews/01 HTTP/1.1
Content-Type: application/json

{
    "id": "01",
    "recipeId": "01",
    "createdAt": "2024-03-17",
    "postedBy": "01",
    "score": 5.7
}

### Delete a review
DELETE http://localhost:8002/api/reviews/01

### Get All reviews for a specific recipe
GET http://localhost:8002/api/recipes/01/reviews

### Get a specific review for a specific recipe
GET http://localhost:8002/api/recipes/01/reviews/01

### Get All reviews for a specific recipe
GET http://localhost:8002/api/profiles/01/reviews

### Get a specific review for a specific recipe
GET http://localhost:8002/api/profiles/01/reviews/01



# Basic recipe service requests

### GET ALL RECIPES
GET http://localhost:8003/api/recipes

### GET Specific recipe
GET http://localhost:8003/api/recipes/01

### ADD A recipe
POST http://localhost:8003/api/recipes HTTP/1.1
Content-Type: application/json

{
    "id": "03",
    "title": "ChICKEN CURRY",
    "ingredients": [
        "pasta",
        "cheese",
        "milk",
        "tomato sauce"
    ],
    "servingSize": "2",
    "cookingTime": "20mins",
    "cuisineType": "Indian",
    "steps": "4",
    "postedById": null
}

### Edit a recipe
PUT http://localhost:8003/api/recipes/03 HTTP/1.1
Content-Type: application/json

{
    "id": "03",
    "title": "pasta",
    "ingredients": [
        "pasta",
        "cheese",
        "milk",
        "tomato sauce"
    ],
    "servingSize": "2",
    "cookingTime": "20mins",
    "cuisineType": "Italian",
    "steps": "4",
    "postedById": "02"
}

### Delete a Recipe
DELETE http://localhost:8003/api/recipes/03

### GET RECIPE FOR SPECIFIC PROFILE
GET http://localhost:8003/api/profiles/01/recipes

### GET A SPECIFIC RECIPE FOR SPECIFIC PROFILE
GET http://localhost:8003/api/profiles/01/recipes/01



# Basic API Gateway GET requests for each service

### Get all profiles
GET http://localhost:8080/api/profiles
### Get all posts
GET http://localhost:8080/api/posts

### Get all recipes
GET http://localhost:8080/api/recipes

### Get all reviews
GET http://localhost:8080/api/reviews


#Testing chat service

### Get All chats
GET http://localhost:8005/api/chats

### Get Specific chat
GET http://localhost:8005/api/chats/01

### Add a chat
POST  http://localhost:8005/api/chats HTTP/1.1
content-type: application/json

{
  "id": "14",
  "user1Id": "15",
  "user2Id": "16",
  "createdAt": "2024-04-28"
}
### Update a chat
PUT   http://localhost:8005/api/chats/01 HTTP/1.1
content-type: application/json

{
  "id": "01",
  "user1Id": "01",
  "user2Id": "02",
  "createdAt": "2024-03-28"
}

### Delete a chat
DELETE    http://localhost:8005/api/chats/01

### Get All messages in a chat
GET http://localhost:8005/api/chats/01/messages

### Get Specific message in a chat
GET http://localhost:8005/api/chats/01/messages/03

### Add a message to a chat
POST http://localhost:8005/api/chats/01/messages HTTP/1.1
content-type: application/json

{
  "id": "09",
  "sender": "we",
  "receiver": "them",
  "content": "Hello, how old are you?",
  "createdAt": "2024-04-28"
}

### Update a message in a chat
PUT http://localhost:8005/api/chats/01/messages/001 HTTP/1.1
content-type: application/json

{
  "id": "001",
  "sender": "user1Id",
  "receiver": "user2Id",
  "content": "Hello, how are you today?",
  "createdAt": "2024-04-28"

}

### Delete a message in a chat
DELETE http://localhost:8005/api/chats/01/messages/001


# Testing Content Personalization Service

### Get personalized posts
GET http://localhost:8007/api/for-you/posts/01

### Get personalized recipes
GET http://localhost:8007/api/for-you/recipes/01


#Testing notification Service

### Get All notifications
GET http://localhost:8006/api/notifications

### Add a notification
POST  http://localhost:8006/api/notifications HTTP/1.1
content-type: application/json

{
  "id": "03",
  "status": "new",
  "userId": "02",
  "message": "i am your new message"
}

### Get All notifications for specific user
GET http://localhost:8006/api/notifications/user/20

### Delete a notification
DELETE http://localhost:8006/api/notifications/03